In [1]:
import numpy as np

In [11]:
# Create Array Using Passing List

Some_List = list(range(1,11))
New_List = list(range(11,21))

Some_Array = np.array(Some_List)
New_Array = np.array(New_List)

In [10]:
# Create Zero Array (All element will be Zero)
n1 = np.zeros((2,3))
n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# Create Array With Specific element (Full method)

n2 = np.full((3,3),10)
n2

In [14]:
# Create Array with Range Function

n3 = np.arange(10,21)
n3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
# Range function with interval
n4 = np.arange(10,50,5)
n4

array([10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
# Random number printing using (random.randint) function 
# random.randint(start,end,total number you want to print)
n5 = np.random.randint(1,100,5)
n5

array([ 4, 81, 36, 34, 52])

In [25]:
# Checking shape of Array
n6 = np.array([[1,2,3],[4,5,6]])
n6.shape

n6.shape = (3,2)



In [40]:
# Joining Numpy Arrays
# vstack(), hstack(), column_stack()

n7 = np.array([range(1,11)])
n8 = np.array([range(11,21)])
n9 = np.array([range(21,31)])

n10 = np.vstack((n7,n8,n9))
n11 = np.hstack((n7,n8))
n12 = np.column_stack((n7,n8,n9))



In [45]:
# Intersection and Difference (Find common Values and Different Values)
# intersect1d()   setdiff1d(first, second)---> Give unique value of First Array

p1 = np.array([range(10,70,10)])
p2 = np.array([range(50,100,10)])   

n13 = np.intersect1d(p1,p2)   # Give common Values
n14 = np.setdiff1d(p1,p2)     # Give Unique value in p1
n15 = np.setdiff1d(p2,p1)     # Give unique value in p2


array([70, 80, 90])

In [57]:
# Mathematics Function in Numpy

np.sum(n7)
np.min(n7)
np.max(n7)
np.median(n7)
np.mean(n7)
np.sum([n7,n8])
np.sum([n7,n8],axis = 0)
np.sum([n7,n8],axis = 1)
np.std(n7)

2.8722813232690143

In [59]:
# Save and Load Numpy Array

# .save(Name,array)
# .load (name.npy)

np.save('my_numpy',n7)

np.load('my_numpy.npy')

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])